name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "✨ [Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: I would like the daily tracker to...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem This Solves
      description: What problem would this feature solve?
      placeholder: This would help users...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: The feature could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative approaches you considered?
      placeholder: We could also...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for usability
        - Critical - Blocks usage
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or other context
      placeholder: Screenshots, links to similar features, etc.
